import { IUserTheme } from './themeDefinitions';

// Theme generated by the typography konfigurator
// https://konfigurator.kaordi.ca - go ahead, it's easy :D

export const theme: IUserTheme = {
  fontSize: 16,
  fontSizeLg: 20,
  fontFamilyBody: '',
  familyCategoryBody: 'sans-serif',
  body: {
    maxWidth: 700,
    lineHeight: 1.8,
    margin: 2,
  },
  bodyWeight: 400,
  headingWeight: 700,
  headings: [
    {
      fontSize: 39,
    },
    {
      fontSize: 31,
    },
    {
      fontSize: 25,
    },
    {
      fontSize: 20,
    },
  ],
  headingsLg: [
    {
      fontSize: 49,
    },
    {
      fontSize: 39,
    },
    {
      fontSize: 31,
    },
    {
      fontSize: 25,
    },
  ],
  colors: {
    text: '#333',
  },
};

export default theme;
